-- V1: initial schema for Splitwise-Lite
-- Uses standard SQL (BIGINT GENERATED ... AS IDENTITY) so the same migration
-- runs on H2 (PostgreSQL mode) for local development and on real PostgreSQL.

CREATE TABLE users (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email           VARCHAR(160)  NOT NULL UNIQUE,
    name            VARCHAR(120)  NOT NULL,
    password_hash   VARCHAR(200)  NOT NULL,
    created_at      TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- "groups" is a reserved keyword in some SQL dialects, so we name the table
-- expense_groups while the JPA entity is simply Group at the domain level.
CREATE TABLE expense_groups (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(120)  NOT NULL,
    description     VARCHAR(500),
    created_by      BIGINT        NOT NULL REFERENCES users(id),
    created_at      TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE group_members (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id        BIGINT        NOT NULL REFERENCES expense_groups(id) ON DELETE CASCADE,
    user_id         BIGINT        NOT NULL REFERENCES users(id),
    joined_at       TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_group_member UNIQUE (group_id, user_id)
);

CREATE INDEX idx_group_members_group ON group_members(group_id);
CREATE INDEX idx_group_members_user  ON group_members(user_id);

CREATE TABLE expenses (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id        BIGINT        NOT NULL REFERENCES expense_groups(id) ON DELETE CASCADE,
    paid_by         BIGINT        NOT NULL REFERENCES users(id),
    description     VARCHAR(200)  NOT NULL,
    amount          NUMERIC(15,2) NOT NULL CHECK (amount > 0),
    split_type      VARCHAR(20)   NOT NULL,
    created_at      TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_expenses_group ON expenses(group_id);
CREATE INDEX idx_expenses_payer ON expenses(paid_by);

CREATE TABLE expense_shares (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    expense_id      BIGINT        NOT NULL REFERENCES expenses(id) ON DELETE CASCADE,
    user_id         BIGINT        NOT NULL REFERENCES users(id),
    share_amount    NUMERIC(15,2) NOT NULL CHECK (share_amount >= 0),
    CONSTRAINT uq_expense_share_user UNIQUE (expense_id, user_id)
);

CREATE INDEX idx_expense_shares_expense ON expense_shares(expense_id);
CREATE INDEX idx_expense_shares_user    ON expense_shares(user_id);

CREATE TABLE settlements (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id        BIGINT        NOT NULL REFERENCES expense_groups(id) ON DELETE CASCADE,
    from_user_id    BIGINT        NOT NULL REFERENCES users(id),
    to_user_id      BIGINT        NOT NULL REFERENCES users(id),
    amount          NUMERIC(15,2) NOT NULL CHECK (amount > 0),
    note            VARCHAR(200),
    settled_at      TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_settlement_distinct_users CHECK (from_user_id <> to_user_id)
);

CREATE INDEX idx_settlements_group ON settlements(group_id);
